import 'twin.macro'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Neon Heard Creative</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main tw="flex flex-col items-center justify-center h-screen">
        <Image src="/nh-logo-bw.png" alt="" width={250} height={250} />
        <p tw="text-yellow-500">Website Coming Soon</p>
      </main>

      <footer></footer>
    </>
  )
}
